name: Running Code Check

on:
  workflow_dispatch:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      NODE_VERSION: 20.9.0

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Enable PackageManager
        run: corepack enable

      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma Client
        run: pnpm -F @olienttech/database prisma generate

      - name: Run Check
        run: pnpm check
